services:
  database:
    image: "postgres:14"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver:
    image: "openmicroscopy/omero-server:5"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"
    ulimits:
      nofile:
        soft: 8192
        hard: 65536

  test:
    build: .
    networks:
      - omero
    depends_on:
      - omeroserver
    environment:
      - HOST=omeroserver
      - ENV=development
      - USERNAME=root
      - PASSWORD=omero
      - PROJECT_ID=151
      - DATA_PATH=omero-napari-data_tests
      - LOG_LEVEL=DEBUG
      - LOG_FILE_PATH=logs/app.log
      - LOG_FORMAT=%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s
      - ENABLE_CONSOLE_LOGGING=True
      - ENABLE_FILE_LOGGING=False
      - LOG_MAX_BYTES=1048576
      - LOG_BACKUP_COUNT=5

networks:
  omero:

volumes:
  database:
  omero:
