[project]
name = "omero-screen-napari"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hh65", email = "hh65@sussex.ac.uk" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
omero-screen-napari = "omero_screen_napari:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
