name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - run: df -h

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - run: df -h

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - run: df -h

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - run: df -h

      - name: Lint with Ruff
        run: uv run ruff check .

      - name: Format with Ruff
        run: uv run ruff format --check .

      - run: df -h

      - name: Type check with mypy
        run: uv run mypy src

      - name: Check if tests exist
        id: check_tests
        run: |
          if [ -d "tests" ] && [ -n "$(ls -A tests 2>/dev/null)" ]; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi

      - run: df -h

      - name: "node-cleanup"
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL

      - run: df -h

      # Docker steps
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3

      - name: Start OMERO server
        run: |
          docker compose up -d database
          sleep 30  # Wait for database
          docker compose up -d omeroserver
          docker compose logs omeroserver  # Let's see the logs
          sleep 240  # Wait for OMERO

      - run: df -h

      - name: "node-cleanup 2"
        run: |
          sudo docker builder prune -a
          sudo docker image prune --all --force

      - run: df -h

      - name: Run tests
        run: |
          docker compose run --rm test uv run pytest tests/ -v --ignore=tests/e2e_tests/

      - run: df -h

      - name: Cleanup
        run: docker compose down -v

      - run: df -h
